<a href="https://colab.research.google.com/github/Valentine199/FreeCodeCamp_DataAnalysis/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import sys
import numpy as np

In [4]:
a = np.array([1,2,3,4])

In [5]:
a[0]

1

In [6]:
a[:3]

array([1, 2, 3])

from, until what elements

In [7]:
a[::2]

array([1, 3])

Array of array indexes. 

In [8]:
a[[0,2,3]]

array([1, 3, 4])

There is typing in numpy eventhrough python doesn't use them

In [10]:
np.array([1,2,3,4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

**Multi dimensional arrays:**

In [20]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [12]:
A.shape

(2, 3)

In [13]:
A.ndim #Dimension size

2

In [14]:
A.size

6

In [16]:
A[1]

array([4, 5, 6])

In [17]:
A[1][0]

4

In [18]:
A[1, 0] # Index the dimensions in a row

4

In [21]:
A[:, :2] # Every row, first 2 elements

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
A[1] = np.array([10,10,10]) #changes row

In [ ]:
A[2] = 99 #  All elements of the 3. row will be 99

In [23]:
A.sum() #all elements

45

In [24]:
A.sum(axis=0) #vertical axis

array([12, 15, 18])

In [25]:
A.sum(axis=1) # horizontal axis

array([ 6, 15, 24])

## Broadcasting and Vectorized operations


In [29]:
b = np.arange(4)

In [27]:
b

array([0, 1, 2, 3])

In [28]:
b + 10 # 10 is added to every element. These are always new arrays

array([10, 11, 12, 13])

In [31]:
b += 100 # B is modified

In [33]:
a

array([1, 2, 3, 4])

In [34]:
a + b # Hvae to have the same shape

array([101, 103, 105, 107])

# Boolean arrays

In [35]:
a = np.arange(4)

In [36]:
a

array([0, 1, 2, 3])

In [37]:
a[[0,-1]]

array([0, 3])

In [38]:
a[[True, False, False, True]]

array([0, 3])

In [39]:
a >= 2

array([False, False,  True,  True])

In [40]:
a[a>=2] # Any boolean operations i valid

array([2, 3])

In [42]:
a.mean()

1.5

In [41]:
a[a > a.mean()]

array([2, 3])

In [44]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
A[A >=5]

array([5, 6, 7, 8, 9])

## Linear algebra

In [46]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [47]:
B = np.array([
    [6,5],
    [4,3],
    [2,1]
])

In [48]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [49]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])